# Generated by Django 4.2.3 on 2023-07-27 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.ImageField(null=True, upload_to='')),
                ('dep_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='department.department')),
            ],
        ),
    ]
