# Generated by Django 4.2.3 on 2023-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
